service: FinGuard-Backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  vpc:
    securityGroupIds:
      - ${env:SG_DAO}
    subnetIds:
      - ${env:PRIVATE_SUBNET_1}
      - ${env:PRIVATE_SUBNET_2}

functions:
  hello:
    handler: handler.hello
    role: ${env:LAMBDA_RDS_ROLE_ARN}
    events:
      - httpApi:
          path: /
          method: any
      - httpApi:
          path: /{proxy+}
          method: any
  
  createUsers:
    handler: handlers/createUsers    
    role: ${env:LAMBDA_RDS_ROLE_ARN}    
    events:
      - httpApi:
          path: /users
          method: post
  
  signIn:
    handler: handlers/signIn
    events:
      - httpApi:
          path: /users/sign-in
          method: post

  getAccountList:
    handler: handlers/getAccountList.getAccountList
    role: ${env:LAMBDA_RDS_ROLE_ARN}
    events:
      - httpApi:
          path: /financial/accounts/{userSub}
          method: get
  
  createAccount:
    handler: handlers/createAccount
    role: ${env:LAMBDA_RDS_ROLE_ARN}
    events:
      - httpApi:
          path: /financial/accounts
          method: post
  
  getAccount:
    handler: handlers/getAccount.getAccount
    role: ${env:LAMBDA_RDS_ROLE_ARN}
    events:
      - httpApi:
          path: /accounts/{accountId}
          method: get

  createTransaction:
    handler: handlers/createTransaction
    events:
      - httpApi:
          path: /banks/accounts
          method: post
