service: FinGuard-Backend-test

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  role: ${env:API_LAMBDA_ROLE_ARN}
  vpc:
    securityGroupIds:
      - ${env:SG_DAO}
    subnetIds:
      - ${env:PRIVATE_SUBNET_1}
      - ${env:PRIVATE_SUBNET_2}

functions:
  rds:
    handler: handlers/rds_handler.hello
    role: ${env:API_LAMBDA_ROLE_ARN}
  sqsPush:
    handler: handlers/sqs_push_handler.send
    role: ${env:API_LAMBDA_ROLE_ARN}
  sqsReceiver:
    handler: handlers/sqs_receive_handler.receive
    role: ${env:SQS_LAMBDA_ROLE_ARN}
    vpc:
      subnetIds:
        - ${env:PRIVATE_SUBNET_1}
        - ${env:PRIVATE_SUBNET_2}
      securityGroupIds:
        - ${env:SG_ALERT}
    events:
      - sqs: ${env:SQS_ARN}
  elasticache:
    handler: handlers/elasticache_handler.handler
    role: ${env:API_LAMBDA_ROLE_ARN}
